function undelfile()  
{  
    mv -i ~/.trash/$@ ./  

}     

trash()  
{  
    mv  $@  ~/.trash/  
}

mkdir -p ~/.trash  
alias rm=trash
alias r=trash  
alias rl='ls ~/.trash'  
alias ur=undelfile  
