#!/usr/bin/env python3
#coding: utf-8

import smtplib
from email.mime.text import MIMEText
from email.header import Header

sender = 'zlt_abc@163.com'
receiver = 'zhuliting@foxmail.com'

subject = 'Hi, zhu_liting'

username = 'xxx@163.com'
password = 'xxx'

msg = MIMEText('Hi, zhu_liting! This main is generated by program.','text','utf-8')
msg['subject'] = subject

smtp = smtplib.SMTP()
smtp.connect('smtp.163.com')
smtp.login(username, password)
smtp.sendmail(sender, receiver, msg.as_string())
smtp.quit()
